/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.github.logicfan.gradle.shadow

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class ShadowJsonTransformerPlugin implements Plugin<Project> {
    void apply(Project project) {
        // do nothing.
    }
}
