/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details take a look at the Writing Custom Plugins chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.0.2/userguide/custom_plugins.html
 */

plugins {
    `java-gradle-plugin`
    groovy
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

val shadowVersion = "7.0.0"

dependencies {
    implementation(gradleApi())
    implementation(localGroovy())
    implementation("gradle.plugin.com.github.jengelman.gradle.plugins:shadow:$shadowVersion")

    testImplementation("org.spockframework:spock-core:2.0-M4-groovy-3.0")
}

gradlePlugin {
    // Define the plugin
    val greeting by plugins.creating {
        id = "com.github.logicfan.gradle.shadow.greeting"
        implementationClass = "com.github.logicfan.gradle.shadow.ShadowJsonTransformerPlugin"
    }
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}
