/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.github.logicfan.gradle.shadow

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'com.github.logicfan.gradle.shadow.greeting' plugin.
 */
class ShadowJsonTransformerPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.github.logicfan.gradle.shadow.greeting")

        then:
        true
    }
}
